Repository beescoop/Obeesdoo, pull requests merged in 2022-08, with the labels that each got.

#420 12.0 split beesdoo inventory
  beesdoo_inventory/README.rst
  beesdoo_inventory/__init__.py
  beesdoo_inventory/__manifest__.py
  beesdoo_inventory/migrations/12.0.3.0.1/post-migration.py
  beesdoo_inventory/models/__init__.py
  beesdoo_inventory/models/stock.py
  beesdoo_inventory/readme/DESCRIPTION.rst
  beesdoo_inventory/static/description/index.html
  beesdoo_inventory/views/stock.xml
  test-requirements.txt
Labels: needs review

#443 [FIX] beesdoo_shift_attendance: remove has_accounting entries
  beesdoo_shift_attendance/views/res_config_settings_view.xml
Labels: needs review, bot is merging ⏳

#444 [ADD] stock move view order
  setup/stock_move_view_line_order/odoo/addons/stock_move_view_line_order
  setup/stock_move_view_line_order/setup.py
  stock_move_view_line_order/README.rst
  stock_move_view_line_order/__init__.py
  stock_move_view_line_order/__manifest__.py
  stock_move_view_line_order/readme/CONTRIBUTORS.rst
  stock_move_view_line_order/readme/DESCRIPTION.rst
  stock_move_view_line_order/static/description/index.html
  stock_move_view_line_order/views/stock_move_line_views.xml
Labels: needs review

#437 12.0 [IMP] beesdoo_shift_swap
  beesdoo_shift/models/planning.py
  beesdoo_shift/models/res_partner.py
  beesdoo_shift_swap/models/dated_template.py
  beesdoo_shift_swap/models/exchange_request.py
  beesdoo_shift_swap/models/planning.py
  beesdoo_shift_swap/models/res_partner.py
  beesdoo_shift_swap/models/shift_swap_mixin.py
  beesdoo_shift_swap/models/solidarity_shift_offer.py
  beesdoo_shift_swap/models/task.py
  beesdoo_shift_swap/tests/test_beesdoo_shift_swap.py
  beesdoo_shift_swap/views/shift_swap_proposale.xml
  beesdoo_shift_swap/views/shift_swap_subscribe.xml
  beesdoo_shift_swap/views/solidarity_shift_offer.xml
  beesdoo_shift_swap/views/solidarity_shift_request.xml
  beesdoo_shift_swap/views/task.xml
  beesdoo_shift_swap/wizard/exchange_wizard.py
  beesdoo_shift_swap/wizard/subscribe_shift_swap.py
  beesdoo_website_shift/i18n/beesdoo_website_shift.pot
  beesdoo_website_shift/i18n/fr_BE.po
  beesdoo_website_shift/i18n/nl_BE.po
  beesdoo_website_shift/views/my_shift_website_templates.xml
  beesdoo_website_shift_swap/controllers/controllers.py
  beesdoo_website_shift_swap/i18n/beesdoo_website_shift_swap.pot
  beesdoo_website_shift_swap/i18n/fr_BE.po
  beesdoo_website_shift_swap/i18n/nl_BE.po
  beesdoo_website_shift_swap/views/exchange_templates.xml
  beesdoo_website_shift_swap/views/solidarity_templates.xml
  beesdoo_website_shift_swap/views/swap_templates.xml
Labels: needs review, bot is merging ⏳

#445 [12.0] beesdoo_print_label : various label template imporovements
  beesdoo_print_label/__manifest__.py
  beesdoo_print_label/readme/CONTRIBUTORS.rst
  beesdoo_print_label/static/css/pricetag_normal_base.scss
  beesdoo_print_label/static/css/pricetag_normal_normal.scss
  beesdoo_print_label/static/description/icon.png
  beesdoo_print_label/views/report_pricetag_normal.xml
Labels: needs review, bot is merging ⏳

#304 [IMP] beesdoo_shift: presence to shift can have variable value
  polln_shift/models/planning.py
  polln_shift/views/shift.xml
Labels: Polln, TODO, needs review, bot is merging ⏳
