Repository beescoop/Obeesdoo, pull requests merged in 2022-11, with the labels that each got.

#462 [FIX] cooperator_worker: remove auto_install
  cooperator_worker/__manifest__.py
Labels: needs review, bot is merging ⏳, approved

#473 update config with copier
  .copier-answers.yml
  .github/workflows/pre-commit.yml
  .gitignore
  README.md
Labels: needs review, bot is merging ⏳

#452 [IMP] b_print_label: show product_brand_id
  beesdoo_print_label/__manifest__.py
  beesdoo_print_label/data/product_print_category.xml
  beesdoo_print_label/readme/newsfragments/452-1.feature.rst
  beesdoo_print_label/readme/newsfragments/452.bugfix.rst
  beesdoo_print_label/readme/newsfragments/452.feature.rst
  beesdoo_print_label/static/css/pricetag_60x38mm.scss
  beesdoo_print_label/views/report_pricetag_normal.xml
Labels: needs review, bot is merging ⏳

#474 [FIX] Update from copier template to fix pre-commit
  .copier-answers.yml
  beesdoo_print_label/README.rst
  beesdoo_print_label/readme/HISTORY.rst
  beesdoo_print_label/static/description/index.html
Labels: needs review, bot is merging ⏳

#472 [FIX] update test-requirements
  oca_dependencies.txt
  test-requirements.txt
Labels: needs review, bot is merging ⏳

#461 [ADD] cooperator_worker_force
  beesdoo_shift/models/res_partner.py
  cooperator_worker/models/res_partner.py
  cooperator_worker_force/README.rst
  cooperator_worker_force/__init__.py
  cooperator_worker_force/__manifest__.py
  cooperator_worker_force/models/__init__.py
  cooperator_worker_force/models/res_partner.py
  cooperator_worker_force/readme/CONTRIBUTORS.rst
  cooperator_worker_force/readme/CREDITS.rst
  cooperator_worker_force/readme/DESCRIPTION.rst
  cooperator_worker_force/static/description/index.html
  cooperator_worker_force/tests/__init__.py
  cooperator_worker_force/tests/test_worker_store.py
  cooperator_worker_force/views/res_partner.xml
  polln_shift/models/res_partner.py
  setup/cooperator_worker_force/odoo/addons/cooperator_worker_force
  setup/cooperator_worker_force/setup.py
Labels: ready to merge, needs review, bot is merging ⏳, approved

#464 [REF] beesdoo_stock: split module
  beesdoo_stock/__init__.py
  beesdoo_stock/__manifest__.py
  beesdoo_stock/i18n/beesdoo_stock.pot
  beesdoo_stock/models/__init__.py
  beesdoo_stock/models/stock.py
  beesdoo_stock/readme/DESCRIPTION.rst
  beesdoo_stock/views/stock_view.xml
Labels: needs review, bot is merging ⏳

#469 [REF] split beesdoo_product_usability->product_main_supplier
  beesdoo_print_label/README.rst
  beesdoo_print_label/readme/HISTORY.rst
  beesdoo_product_usability/__init__.py
  beesdoo_product_usability/__manifest__.py
  beesdoo_product_usability/i18n/beesdoo_product_usability.pot
  beesdoo_product_usability/models/__init__.py
  beesdoo_product_usability/models/beesdoo_product.py
  beesdoo_product_usability/views/beesdoo_product.xml
  product_main_supplier/models/product_template.py
  product_main_supplier/readme/DESCRIPTION.rst
  product_main_supplier/readme/ROADMAP.rst
Labels: needs review, bot is merging ⏳

#468 12.0 rename beesdoo pos reporting
  beesdoo_pos_reporting/__init__.py
  beesdoo_pos_reporting/__manifest__.py
  beesdoo_pos_reporting/i18n/beesdoo_pos_reporting.pot
  beesdoo_pos_reporting/models/__init__.py
  beesdoo_pos_reporting/models/res_partner.py
  beesdoo_pos_reporting/readme/CONTRIBUTORS.rst
  beesdoo_pos_reporting/readme/DESCRIPTION.rst
Labels: needs review

#478 12.0 fix dependencies
  beesdoo_inventory/__manifest__.py
  beesdoo_pos_coop_status/__manifest__.py
Labels: needs review, bot is merging ⏳

#477 [IMP] [eater_]member_card: Do not set barcode on eaters
  eater_member_card/__manifest__.py
  eater_member_card/migrations/12.0.1.1.0/post-migration.py
  eater_member_card/models/partner.py
  eater_member_card/readme/newsfragments/477.bugfix.rst
  member_card/models/partner.py
Labels: needs review, bot is merging ⏳

#479 [REF] shift_portal_eater: portal_eater
  beesdoo_website_eater/__manifest__.py
  portal_eater/README.rst
  portal_eater/__init__.py
  portal_eater/__manifest__.py
  portal_eater/controllers/__init__.py
  portal_eater/controllers/main.py
  portal_eater/i18n/portal_eater.pot
  portal_eater/readme/CONTRIBUTORS.rst
  portal_eater/readme/DESCRIPTION.rst
  portal_eater/static/description/index.html
  portal_eater/views/portal_eater_templates.xml
  setup/portal_eater/odoo/addons/portal_eater
  setup/portal_eater/setup.py
  setup/shift_portal_eater/odoo/addons/shift_portal_eater
Labels: needs review, bot is merging ⏳

#480 [FIX] pos_shift_partner_can_shop: assets
  pos_shift_partner_can_shop/views/assets.xml
Labels: needs review, bot is merging ⏳

#481 [REM] beesdoo_pos_coop_status: remove refactored files
  beesdoo_pos_coop_status/__manifest__.py
  beesdoo_pos_coop_status/static/src/css/coop_status.css
  beesdoo_pos_coop_status/static/src/js/models.js
  beesdoo_pos_coop_status/static/src/js/screens.js
  beesdoo_pos_coop_status/static/src/xml/pos.xml
  beesdoo_pos_coop_status/views/assets.xml
Labels: needs review, bot is merging ⏳
